### ISSUE TITLE
Facing an issue when cloning new project 

### ISSUE THREAD

**Issue by kush4545** [netless-io/fastboard#31] opened 2024-02-21 06:19 UTC
At the time of new npm install this issue is hppening with fastboard.

Uncaught TypeError: Cannot set properties of undefined (setting 'type')
    at push../node_modules/white-web-sdk/node_modules/mathjs/lib/esm/type/fraction/Fraction.js.Object.isClass

**Comment by hyrious** [comment] 2024-02-21 06:33
Closing as a duplicate of #30.

**Closed by hyrious** 2024-02-21 06:33 UTC
